[fix] KeyValueParser: validate keys only when known names are set
Addressing:
```
(E) Error: parsed key is not in key set: 'RuleFile'
ERROR: KeyValueParser: Parser: Invalid key
```

Resolves: https://github.com/USBGuard/usbguard/issues/269