Docker: Bump to Alpine 3.21 to fix CI
Previous error was:
> ERROR: unable to select packages:
>   libqb-dev (no such package):
>     required by: world[libqb-dev]
>   pegtl (no such package):
>     required by: world[pegtl]